### PR TITLE
Added step to publish storybook to GH-Pages

### PR DESCRIPTION
**Pull request by BetimBeja**
Hi David,
I added an action to publish the component storybook in the GitHub Pages of your repository 😉

### CODE REVIEW

**Comment by drivardxrm** [comment]
Hi @BetimBeja,
I was waiting to make some other adjustments before publishing the storybook.
Unfortunately, I didn't had the time in the past week.

I see that you added some changes to the stories too, I'll have a look and integrate your PR soon.
Thanks

**Comment by BetimBeja** [comment]
It is a continuous improvement process

**Comment by drivardxrm** [comment]
Awesome, the storybook is published.

I was unable to make the component update after a a getOutput call.
Your PR made it work ;)

I have added an intro page to the Storybook with a mention of your library and company.

image

**Comment by BetimBeja** [comment]
Thank you so much David 😄 
`*` I will "borrow" the storybook intro for my components also.

**Pull request merged**
